# -*- coding: utf-8 -*-
"""Visualization using python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14arwFPeqFrrhfge4PprQTX3rWV7G3-0s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path="https://raw.githubusercontent.com/chirudukuru/DMDW/main/Toyota.csv"

import pandas as pd
data=pd.read_csv(path)

data

data.head()

data.tail()

data.dropna(axis=0,inplace=True)

data.shape

data.head()

plt.scatter(data['Age'],data['Price'],c='red')
plt.xlabel('Age(months)')
plt.ylabel('Price')
plt.show()

plt.hist(data['KM'])
plt.show()

plt.hist(data['KM'])

plt.hist(data['KM'],color='orange',edgecolor='white',bins=5)
plt.title=("histogram of kilometer")
plt.xlabel("frequencies")
plt.ylabel("KM")
plt.show()

import seaborn as sns

sns.set(style='darkgrid')
sns.regplot(x=data['Age'],y=data['Price'])

sns.set(style='darkgrid')
sns.regplot(x=data['Age'],y=data['Price'],marker='*',fit_reg=False)

sns.distplot(data['Age'])

sns.displot(data['Age'],kde=False) #kde=kernel density estimator if we declare it false then that de line got removed

sns.distplot(data['Age'],kde=False,bins=5)

sns.countplot(x="FuelType",data=data)

sns.countplot(x="FuelType",data=data,hue='Automatic')#hue

sns.boxplot(y=data['Price'])

sns.boxplot(x=data['Age'],y=data['Price'],data=data,hue='Automatic')